# Please be aware of changing a function here can cause the plugin til malfunction.
# Consider to use the ingame GUI the make all settings (/enchantcontrol)
# Values can be changed here, but at own risk!!!
# Support will NOT be provided, if you have manfully changed the config!

configVersion: 1.1
setup: false


enchants:
  99:
    name: "Curse Of Programming"
    bukkitName: "PROGRAMMING_CURSE"
    ver: 1.11
    disabled: true
    custom: true
    maxLevel: 3
    item: PAPER

