name: EnchantControl
version: 1.3.0
author: Arkobat
main: com.gmail.arkobat.EnchantControl.EnchantControl
description: Take back control of all enchantments
softdepend: [CustomEnchants]
commands:
  EnchantControl:
    description: Opens a GUI to toggle enchants

permissions:
   EnchantControl.admin:
     description: Permission to use the plugin